[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Runtime arena with generational ids for SWC."
documentation = "https://rustdoc.swc.rs/swc_arena/"
edition       = { workspace = true }
license       = { workspace = true }
name          = "swc_arena"
repository    = { workspace = true }
version       = "0.1.0"

[lib]
bench = false

[features]
serde-impl = ["dep:serde"]

[dependencies]
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
codspeed-criterion-compat = { workspace = true }
swc_malloc                = { version = "1.2.4", path = "../swc_malloc" }

[[bench]]
harness = false
name    = "bench"
