[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Arena-based ES AST definitions."
documentation = "https://rustdoc.swc.rs/swc_es_ast/"
edition       = { workspace = true }
license       = { workspace = true }
name          = "swc_es_ast"
repository    = { workspace = true }
version       = "0.1.0"

[lib]
bench = false

[features]
default = []
encoding-impl = ["dep:cbor4ii"]
serde-impl = [
  "dep:serde",
  "swc_arena/serde-impl",
]

[dependencies]
serde = { workspace = true, features = ["derive"], optional = true }

cbor4ii = { workspace = true, features = ["use_std"], optional = true }
swc_arena = { version = "0.1.0", path = "../swc_arena", default-features = false }
swc_atoms = { version = "9.0.0", path = "../swc_atoms", default-features = false }
swc_common = { version = "19.0.0", path = "../swc_common" }

[dev-dependencies]
serde_json = { workspace = true }
