[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Compatibility layer for the ECMAScript standard"
documentation = "https://rustdoc.swc.rs/swc_ecma_transformer/"
edition       = { workspace = true }
include       = ["Cargo.toml", "src/**/*.rs"]
license       = { workspace = true }
name          = "swc_ecma_transformer"
repository    = { workspace = true }
version       = "10.0.0"

[features]
default = []
es3 = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(swc_ast_unknown)'] }

[dependencies]
rustc-hash = { workspace = true }
swc_atoms = { version = "9.0.0", path = "../swc_atoms" }
swc_common = { version = "19.0.0", path = "../swc_common" }
swc_ecma_ast = { version = "21.0.0", path = "../swc_ecma_ast" }
swc_ecma_compat_regexp = { version = "2.0.0", path = "../swc_ecma_compat_regexp" }
swc_ecma_hooks = { version = "0.5.0", path = "../swc_ecma_hooks" }
swc_ecma_regexp = { version = "0.8.0", path = "../swc_ecma_regexp" }
swc_ecma_transforms_base = { version = "38.0.0", path = "../swc_ecma_transforms_base" }
swc_ecma_utils = { version = "27.0.0", path = "../swc_ecma_utils" }
swc_ecma_visit = { version = "21.0.0", path = "../swc_ecma_visit", features = [
    "path",
] }
tracing = { workspace = true }
